version: "3.8"

services:

  prometheus:
    image: prom/prometheus:v2.30.3
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"

  grafana:
    depends_on:
      - jaeger
      - prometheus
    image: grafana/grafana:latest
    ports:
      - "3000:3000"