version: "3.8"

services:

  prometheus:
    image: prom/prometheus:v2.30.3
    environment:
      LISTEN_PORT: '9090'
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"