global:
  scrape_interval: 60s
remote_write:
  - url: grafanaCloudPrometheusPushUrl
    basic_auth:
      username: grafanaCloudUser
      password: grafanaCloudUserToken
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]