global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: java-otel-grafana-app
    scheme: http
    static_configs:
      - targets: ["host.docker.internal:9464"]
  - job_name: jaeger
    scheme: http
    static_configs:
      - targets: [ "jaeger:14269" ]